// <auto-generated />
namespace CF_Console_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ToDoItemstableClosedtonullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToDoItemstableClosedtonullable));
        
        string IMigrationMetadata.Id
        {
            get { return "202103231629000_ToDoItems table Closed to nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
